server:
  port: 8082

# spring boot admin client配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# feign配置
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        loggerLevel: FULL
  compression:
    request:
      enabled: true
    response:
      enabled: true
  httpclient:
    connection-timeout: 60000
    enabled: true
