server:
  port: 8081

# spring boot admin server配置
spring:
  boot:
    admin:
      context-path: /admin
      ui:
        cache:
          no-cache: true

# feign配置
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        loggerLevel: FULL
  compression:
    request:
      enabled: true
    response:
      enabled: true
  httpclient:
    connection-timeout: 60000
    enabled: true

# jasypt加密配置
jasypt:
  encryptor:
    password: wakening
    algorithm: PBEWITHHMACSHA512ANDAES_256

# mybatis配置
mybatis:
  configuration:
    # 开启下划线转驼峰
    map-underscore-to-camel-case: true



